/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xu81.java.tools.view;

import com.xu81.java.tools.model.ConnectionBean;
import com.xu81.java.tools.util.DBEngine;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JButton;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabPanel = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConnection = new javax.swing.JMenu();
        miNewConn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miDisconn = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        miImp = new javax.swing.JMenuItem();
        miEmp = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        miHelp = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MongoGUI");
        setName("mainframe");

        menuConnection.setMnemonic(KeyEvent.VK_C);
        menuConnection.setText("数据库连接(C)");

        miNewConn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNewConn.setMnemonic(KeyEvent.VK_N);
        miNewConn.setText("新连接(N)");
        miNewConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewConnActionPerformed(evt);
            }
        });
        menuConnection.add(miNewConn);
        miNewConn.getAccessibleContext().setAccessibleName("miNewConn");

        menuConnection.add(jSeparator1);

        miDisconn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        miDisconn.setMnemonic(KeyEvent.VK_D);
        miDisconn.setText("断开连接(D)");
        menuConnection.add(miDisconn);
        miDisconn.getAccessibleContext().setAccessibleName("miDisconn");

        menuConnection.add(jSeparator2);

        miExit.setMnemonic(KeyEvent.VK_X);
        miExit.setText("退出(X)");
        menuConnection.add(miExit);
        miExit.getAccessibleContext().setAccessibleName("miExit");

        jMenuBar1.add(menuConnection);
        menuConnection.getAccessibleContext().setAccessibleName("connectionMenu");

        menuTools.setMnemonic(KeyEvent.VK_T);
        menuTools.setText("工具(T)");

        miImp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        miImp.setMnemonic(KeyEvent.VK_I);
        miImp.setText("导入(I)");
        menuTools.add(miImp);
        miImp.getAccessibleContext().setAccessibleName("miImp");

        miEmp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miEmp.setMnemonic(KeyEvent.VK_E);
        miEmp.setText("导出(E)");
        menuTools.add(miEmp);
        miEmp.getAccessibleContext().setAccessibleName("miEmp");

        jMenuBar1.add(menuTools);
        menuTools.getAccessibleContext().setAccessibleName("toolsMenu");

        menuHelp.setMnemonic(KeyEvent.VK_H);
        menuHelp.setText("帮助(H)");

        miHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miHelp.setText("帮助");
        menuHelp.add(miHelp);
        miHelp.getAccessibleContext().setAccessibleName("miHelp");

        miAbout.setMnemonic(KeyEvent.VK_A);
        miAbout.setText("关于(A)");
        menuHelp.add(miAbout);
        miAbout.getAccessibleContext().setAccessibleName("miAbout");

        jMenuBar1.add(menuHelp);
        menuHelp.getAccessibleContext().setAccessibleName("helpMenu");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        mainTabPanel.getAccessibleContext().setAccessibleName("content");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNewConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewConnActionPerformed
        NewConnectionDlg dlg = new NewConnectionDlg(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_miNewConnActionPerformed

    public static void newConnection(ConnectionBean cb){
        DBEngine engine = DBEngine.getInstance(cb);
        List<String> dbs = engine.showDbs();
        Map<String,Set<String>> map = new HashMap<String, Set<String>>();
        for(String db : dbs){
            Set<String> colls = engine.showCollections(db);
            map.put(db, colls);
        }
        TabPanel tp = new TabPanel(dbs,map,cb);
        mainTabPanel.addTab(cb.getName(), tp);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private static javax.swing.JTabbedPane mainTabPanel;
    private javax.swing.JMenu menuConnection;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miDisconn;
    private javax.swing.JMenuItem miEmp;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miHelp;
    private javax.swing.JMenuItem miImp;
    private javax.swing.JMenuItem miNewConn;
    // End of variables declaration//GEN-END:variables
}
