/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xu81.java.tools.view;

import com.xu81.java.tools.model.ConnectionBean;
import com.xu81.java.tools.util.ConfigUtil;
import com.xu81.java.tools.util.DBEngine;
import java.util.Map;
import javax.swing.JOptionPane;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Administrator
 */
public class NewConnectionDlg extends javax.swing.JDialog {

    /**
     * Creates new form NewConnectionDlg
     */
    public NewConnectionDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();
    }

    /**
     * init connection data
     */
    private void initData() {
        Map<String, ConnectionBean> conns = ConfigUtil.getConns();
        if (CollectionUtils.isEmpty(conns.keySet())) {
            disableBtn();
        } else {
            enableText();
        }
        for (String cbName : conns.keySet()) {
            cbSavedConn.addItem(cbName);
        }
    }

    /**
     * disable btn group
     */
    private void disableBtn() {
        btnCopyConn.setEnabled(false);
        btnSaveConn.setEnabled(false);
        btnRenameConn.setEnabled(false);
        btnDelConn.setEnabled(false);
        btnConn.setEnabled(false);
        btnTestConn.setEnabled(false);
    }

    /**
     * enable text group
     */
    private void enableText() {
        txtServerConn.setEnabled(true);
        txtPortConn.setEnabled(true);
        txtCollectionConn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewConn = new javax.swing.JButton();
        btnCopyConn = new javax.swing.JButton();
        btnSaveConn = new javax.swing.JButton();
        btnRenameConn = new javax.swing.JButton();
        btnDelConn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbSavedConn = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtServerConn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPortConn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCollectionConn = new javax.swing.JTextField();
        btnTestConn = new javax.swing.JButton();
        btnCloseConn = new javax.swing.JButton();
        btnConn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnNewConn.setText("新建");
        btnNewConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewConnActionPerformed(evt);
            }
        });

        btnCopyConn.setText("复制");

        btnSaveConn.setText("保存");

        btnRenameConn.setText("重命名");

        btnDelConn.setText("删除");

        jLabel1.setText("保存的连接:");

        cbSavedConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSavedConnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MongoDB"));

        jLabel2.setText("地址:");

        txtServerConn.setEnabled(false);

        jLabel5.setText("端口:");

        txtPortConn.setEnabled(false);

        jLabel6.setText("数据集:");

        txtCollectionConn.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtServerConn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtPortConn)
                    .addComponent(txtCollectionConn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtServerConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPortConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCollectionConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtServerConn.getAccessibleContext().setAccessibleName("txtServerConn");
        txtPortConn.getAccessibleContext().setAccessibleName("txtPortConn");
        txtCollectionConn.getAccessibleContext().setAccessibleName("txtCollectionConn");

        btnTestConn.setText("测试连接");
        btnTestConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestConnActionPerformed(evt);
            }
        });

        btnCloseConn.setText("取  消");
        btnCloseConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseConnActionPerformed(evt);
            }
        });

        btnConn.setText("连  接");
        btnConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCloseConn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTestConn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbSavedConn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnNewConn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCopyConn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSaveConn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRenameConn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDelConn)))
                            .addGap(10, 10, 10))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSaveConn)
                    .addComponent(btnRenameConn)
                    .addComponent(btnNewConn)
                    .addComponent(btnCopyConn)
                    .addComponent(btnDelConn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSavedConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTestConn)
                    .addComponent(btnCloseConn)
                    .addComponent(btnConn))
                .addContainerGap())
        );

        btnNewConn.getAccessibleContext().setAccessibleName("btnNewConn");
        btnCopyConn.getAccessibleContext().setAccessibleName("btnCopyConn");
        btnSaveConn.getAccessibleContext().setAccessibleName("btnSaveConn");
        btnRenameConn.getAccessibleContext().setAccessibleName("btnRenameConn");
        btnDelConn.getAccessibleContext().setAccessibleName("btnDelConn");
        cbSavedConn.getAccessibleContext().setAccessibleName("cbSavedConn");
        btnTestConn.getAccessibleContext().setAccessibleName("btnTestConn");
        btnCloseConn.getAccessibleContext().setAccessibleName("btnCloseConn");
        btnConn.getAccessibleContext().setAccessibleName("btnConn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewConnActionPerformed
        String name = JOptionPane.showInputDialog("请输入新连接名称:");
        if(!StringUtils.isEmpty(name)){
            cbSavedConn.addItem(name);
            cbSavedConn.setSelectedItem(name);
            enableText();
            setTextContent(null);
            btnConn.setEnabled(true);
            btnTestConn.setEnabled(true);
            btnSaveConn.setEnabled(true);
        }
    }//GEN-LAST:event_btnNewConnActionPerformed

    private void btnConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnActionPerformed
        this.dispose();
        Map<String,ConnectionBean> conns = ConfigUtil.getConns();
        ConnectionBean cb = conns.get(StringUtils.trim(cbSavedConn.getSelectedItem().toString()));
        MainFrame.newConnection(cb!=null?cb:initNewConnectionBean());
    }//GEN-LAST:event_btnConnActionPerformed

    private void cbSavedConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSavedConnActionPerformed
        String cbName = cbSavedConn.getSelectedItem().toString();
        Map<String, ConnectionBean> conns = ConfigUtil.getConns();
        ConnectionBean cb = conns.get(cbName);
        setTextContent(cb);
    }//GEN-LAST:event_cbSavedConnActionPerformed

    private void btnCloseConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseConnActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseConnActionPerformed

    private void btnTestConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestConnActionPerformed
        ConnectionBean cb = initNewConnectionBean();
        DBEngine engine = DBEngine.getInstance(cb);
        JOptionPane.showMessageDialog(this, engine.testConn()?"连接成功":"连接失败");
    }//GEN-LAST:event_btnTestConnActionPerformed
    
    private ConnectionBean initNewConnectionBean(){
        return new ConnectionBean(
                    StringUtils.trim(cbSavedConn.getSelectedItem().toString()),
                    StringUtils.trim(txtServerConn.getText()),
                    StringUtils.trim(txtPortConn.getText()),
                    StringUtils.trim(txtCollectionConn.getText())
                );
    }
    
    private void setTextContent(ConnectionBean cb) {
        txtServerConn.setText(cb==null?"":cb.getServer());
        txtPortConn.setText(cb==null?"":cb.getPort());
        txtCollectionConn.setText(cb==null?"":cb.getDbName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseConn;
    private javax.swing.JButton btnConn;
    private javax.swing.JButton btnCopyConn;
    private javax.swing.JButton btnDelConn;
    private javax.swing.JButton btnNewConn;
    private javax.swing.JButton btnRenameConn;
    private javax.swing.JButton btnSaveConn;
    private javax.swing.JButton btnTestConn;
    private javax.swing.JComboBox cbSavedConn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCollectionConn;
    private javax.swing.JTextField txtPortConn;
    private javax.swing.JTextField txtServerConn;
    // End of variables declaration//GEN-END:variables
}
